### ISSUE TITLE
Develop process from 3D model to kinematic profile for attached rigid bodies

### ISSUE THREAD

**Issue by codyallard28** [lasp/xmera#19]

**Comment by patkenneally** [comment]
@codyallard28 or @leahkiner  Are you able to clarify this issue for me? I'm migrating stuff into Jira and want to capture this one accurately. No rush.

**Comment by codyallard28** [comment]
@patkenneally @leahkiner 
3D models store kinematics information about how components can move with respect to an assembly.
This issue is meant to research the methods that could be used to stimulate the 3D model based on inputs of an actuator and how that is translated into kinematics data. i.e. position, attitude.
